
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tm.rocketlab.global
  resources:
  - sites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tm.rocketlab.global
  resources:
  - sites/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tm.rocketlab.global
  resources:
  - tmsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tm.rocketlab.global
  resources:
  - tmsources/status
  verbs:
  - get
  - patch
  - update
