# permissions for end users to view tmsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tmsource-viewer-role
rules:
- apiGroups:
  - tm.rocketlab.global
  resources:
  - tmsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tm.rocketlab.global
  resources:
  - tmsources/status
  verbs:
  - get
